pipeline {
    agent any
    
    parameters {
        choice(
            choices: ['Clonar repositorio', 'Compilar y empaquetar', 'Despliegue en desarrollo'],
            description: 'Seleccione la etapa que desea ejecutar',
            name: 'ETAPA_EJECUTAR'
        )
    }

     environment {
            // Definir el puerto en el que deseas ejecutar la aplicación Spring Boot
            PORT = '9595'
            URL = '/Users/gabriel/Applications'
    }

    stages {
        stage('Clonar repositorio') {
            steps {
                git 'URL_DEL_REPOSITORIO_GIT'
            }
        }
        stage('Compilar y empaquetar') {
            steps {
                // Aquí agregarías los comandos para compilar y empaquetar tu proyecto, ya sea con Gradle o Maven.
                // Por ejemplo, para Gradle: sh './gradlew clean build'
                // Y para Maven: sh 'mvn clean package'
            }
        }
        stage('Desplegar desarrollo') {
            steps {
                // Aquí agregarías los comandos para desplegar tu aplicación en el entorno de desarrollo.
                // Por ejemplo, para Spring Boot: sh 'java -jar nombre-del-jar.jar'
            }
        }
        stage('Desplegar producción') {
            steps {
                // Aquí agregarías los comandos para desplegar tu aplicación en el entorno de producción.
                // Pueden ser comandos para copiar archivos a servidores, configurar servicios, etc.
            }
        }
        stage('Despliegue en desarrollo') {
            steps {
                // Copiar el archivo JAR empaquetado a la carpeta de destino
                sh 'cp gradle/wrapper/gradle-wrapper.jar ${URL}/'

                // Ejecutar la aplicación en el puerto definido
                sh 'java -jar ${URL}/gradle-wrapper.jar --server.port=${PORT}'
            }
        }
    }
}
